-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 13, 2025 at 03:08 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `graduate`
--

-- --------------------------------------------------------

--
-- Table structure for table `features`
--

CREATE TABLE `features` (
  `id` int(11) NOT NULL,
  `feature` text NOT NULL,
  `category_id` varchar(191) NOT NULL,
  `pro` varchar(191) NOT NULL,
  `core` varchar(191) NOT NULL,
  `elite` varchar(191) NOT NULL,
  `core_tooltip` text DEFAULT NULL,
  `pro_tooltip` text DEFAULT NULL,
  `elite_tooltip` text DEFAULT NULL,
  `_order` int(11) NOT NULL DEFAULT 1,
  `slug` varchar(191) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `features`
--

INSERT INTO `features` (`id`, `feature`, `category_id`, `pro`, `core`, `elite`, `core_tooltip`, `pro_tooltip`, `elite_tooltip`, `_order`, `slug`) VALUES
(1, '24-Credit-Graduation Standard Track', '1', 'Yes', 'Yes', 'Yes', 'Standard program with the full course requirements for a Florida high school diploma. Generally preferred for national or international students planning to pursue higher education at colleges or universities.', 'Standard program with the full course requirements for a Florida high school diploma. Generally preferred for national or international students planning to pursue higher education at colleges or universities.', 'Standard program with the full course requirements for a Florida high school diploma. Generally preferred for national or international students planning to pursue higher education at colleges or universities.', 1, ''),
(2, '24-Credit-Graduation Honors Track', '1', 'Yes', 'Yes', 'Yes', 'Honors program based on the full 24-credit graduation requirements for a Florida high school diploma, awarded to national and international students with a GPA of 3.5 or higher. Demonstrates advanced academic achievement and stronger preparation for higher education.', 'Honors program based on the full 24-credit graduation requirements for a Florida high school diploma, awarded to national and international students with a GPA of 3.5 or higher. Demonstrates advanced academic achievement and stronger preparation for higher education.', 'Honors program based on the full 24-credit graduation requirements for a Florida high school diploma, awarded to national and international students with a GPA of 3.5 or higher. Demonstrates advanced academic achievement and stronger preparation for higher education.', 2, ''),
(3, '18-Credit-ACCEL Graduation Track', '1', 'Yes', 'Yes', 'Yes', 'Accelerated program with fewer courses that meets the minimum Florida diploma requirements. May limit options for admission to certain colleges or universities, depending on institutional or country-specific criteria.', 'Accelerated program with fewer courses that meets the minimum Florida diploma requirements. May limit options for admission to certain colleges or universities, depending on institutional or country-specific criteria.', 'Accelerated program with fewer courses that meets the minimum Florida diploma requirements. May limit options for admission to certain colleges or universities, depending on institutional or country-specific criteria.', 3, ''),
(4, 'Credit Transfer Track', '1', 'Yes', 'Yes', 'Yes', 'Up to 75% of previously earned credits from state-recognized or accredited schools may be transferred after transcript evaluation. At least 25% of all credits must be completed at our school to qualify for graduation.', 'Up to 75% of previously earned credits from state-recognized or accredited schools may be transferred after transcript evaluation. At least 25% of all credits must be completed at our school to qualify for graduation.', 'Up to 75% of previously earned credits from state-recognized or accredited schools may be transferred after transcript evaluation. At least 25% of all credits must be completed at our school to qualify for graduation.', 4, ''),
(5, 'Rolling Enrollment', '1', 'Yes', 'Yes', 'Yes', 'Rolling enrollment allows students to start their studies at any time during the year without waiting for a specific semester or term.', 'Rolling enrollment allows students to start their studies at any time during the year without waiting for a specific semester or term.', 'Rolling enrollment allows students to start their studies at any time during the year without waiting for a specific semester or term.', 5, 'rolling-enrollment'),
(6, '12-month Round Schooling', '1', 'Yes', 'Yes', 'Yes', 'Provides full-year learning and examination opportunities, allowing students to progress and complete their studies continuously without fixed academic terms.', 'Provides full-year learning and examination opportunities, allowing students to progress and complete their studies continuously without fixed academic terms.', 'Provides full-year learning and examination opportunities, allowing students to progress and complete their studies continuously without fixed academic terms.', 6, ''),
(8, 'Cross-Grade Learning', '1', 'Yes', 'Yes', 'Yes', 'Allows students to take courses across different grade levels, enabling flexible scheduling based on individual strengths, interests, and personal timelines while fulfilling all required core and elective courses.', 'Allows students to take courses across different grade levels, enabling flexible scheduling based on individual strengths, interests, and personal timelines while fulfilling all required core and elective courses.', 'Allows students to take courses across different grade levels, enabling flexible scheduling based on individual strengths, interests, and personal timelines while fulfilling all required core and elective courses.', 7, ''),
(11, 'Full Access to all Graduation Courses anytime', '2', 'Yes', 'Yes', 'Yes', 'Provides unrestricted access to all graduation courses at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 'Provides unrestricted access to all graduation courses at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 'Provides unrestricted access to all graduation courses at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 0, ''),
(12, 'Full Access to the course library', '2', 'Yes', 'Yes', 'Yes', 'Provides unrestricted access to the full course library at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 'Provides unrestricted access to the full course library at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 'Provides unrestricted access to the full course library at any time, allowing students to complete all subjects required for the 24-credit graduation track without yearly course limits.', 0, ''),
(15, 'Real-Time Performance Monitoring', '2', 'Yes', 'Yes', 'Yes', 'Provides real-time insights into academic performance for both students and parents, allowing continuous monitoring of progress and early response to any performance deviations.', 'Provides real-time insights into academic performance for both students and parents, allowing continuous monitoring of progress and early response to any performance deviations.', 'Provides real-time insights into academic performance for both students and parents, allowing continuous monitoring of progress and early response to any performance deviations.', 0, ''),
(16, 'AI-StudyMentors 24/7 related to subject', '2', 'Fair Use Access (Smart)', 'Fair Use Access (Lite)', 'Fair Use Access (Smart)', '<p>Each subject is supported by its own AI Study Mentor, available 24/7 to assist with questions, explanations, and learning guidance directly related to that specific subject. Fair Use Access (Lite) plan includes up to 500 questions per month.</p>', '<p>Each subject is supported by its own AI Study Mentor, available 24/7 to assist with questions, explanations, and learning guidance directly related to that specific subject. Fair Use Access (Smart) plan includes up to 1,200 questions per month.</p>', '<p>Each subject is supported by its own AI Study Mentor, available 24/7 to assist with questions, explanations, and learning guidance directly related to that specific subject. Fair Use Access (Smart) plan includes up to 1,200 questions per month.</p>', 0, ''),
(18, 'PSAT Prep-Course with Pre-Exam', '3', 'Full Access', 'Add-on (extra charge)', 'Full Access', '<p>PSAT preparation course with a simulated exam available as an optional add-on for an additional fee.</p>', '<p>PSAT preparation course with a simulated exam included in the plan.</p>', '<p>PSAT preparation course with a simulated exam included in the plan.</p>', 1, 'psat-prep-course'),
(19, 'SAT/ACT Prep-Course with Pre-Exam', '3', 'Full Access', 'Add-on (extra charge)', 'Full Access', 'SAT or ACT preparation course with a simulated exam available as an optional add-on for an additional fee.', 'SAT or ACT preparation course with a simulated exam included in the plan.', 'SAT or ACT preparation course with a simulated exam included in the plan.', 2, ''),
(20, 'Advanced Placement Prep-Courses with Pre-Exams', '3', '1 per year', 'Add-on (extra charge)', '2 per year', 'Advanced Placement preparation courses with a simulated exam available as an optional add-on for an additional fee.', 'Advanced Placement preparation courses with a simulated exam included in the plan (1 courses of choice within 12 months).', 'Advanced Placement preparation courses with a simulated exam included in the plan (2 courses of choice within 12 months).', 3, ''),
(21, 'Career & Technical Education (CTE) Prep-Courses with Pre-Exams', '3', '2 per year', 'Add-on (extra charge)', '4 per year', 'Career & Technical Education preparation courses with a simulated exam available as an optional add-on for an additional fee.', 'Career & Technical Education preparation courses with a simulated exam included in the plan (2 courses of choice within 12 months).', 'Career & Technical Education preparation courses with a simulated exam included in the plan (4 courses of choice within 12 months).', 5, ''),
(28, 'Ambassador Program', '4', 'Yes', 'Yes', 'Yes', 'Allows students to share their school experience, refer others, and receive special benefits through a dynamic reward system.', 'Allows students to share their school experience, refer others, and receive special benefits through a dynamic reward system.', '1Allows students to share their school experience, refer others, and receive special benefits through a dynamic reward system.', 1, ''),
(29, 'Freshman Kit', '4', 'Yes', 'Yes', 'Yes', 'Welcome Kit filled with trendy and practical gear designed to match your vibe and kick off your high school experience in style.', 'Welcome Kit filled with trendy and practical gear designed to match your vibe and kick off your high school experience in style.', 'Welcome Kit filled with trendy and practical gear designed to match your vibe and kick off your high school experience in style.', 1, ''),
(30, 'Access to Awards Programs', '4', 'Yes', 'Yes', 'Yes', 'Includes recognition through the President’s Education Awards Program (PEAP), the American Citizenship Award, and additional institutional recognitions for outstanding performance.', 'Includes recognition through the President’s Education Awards Program (PEAP), the American Citizenship Award, and additional institutional recognitions for outstanding performance.', 'Includes recognition through the President’s Education Awards Program (PEAP), the American Citizenship Award, and additional institutional recognitions for outstanding performance.', 1, ''),
(31, 'Group Learning Sessions', '4', 'Yes', 'Add-on (extra charge)', 'Yes', 'Facilitates collaborative progress review, shared identification of learning gaps, collective time management strategies, task coordination, short-term goal planning, and study technique exchange to enhance group performance available as an optional add-on for an additional fee.', 'Facilitates collaborative progress review, shared identification of learning gaps, collective time management strategies, task coordination, short-term goal planning, and study technique exchange to enhance group performance (every two weeks, 45 minutes).', 'Facilitates collaborative progress review, shared identification of learning gaps, collective time management strategies, task coordination, short-term goal planning, and study technique exchange to enhance group performance (every two weeks, 45 minutes).', 1, ''),
(32, 'Personal Mentoring Sessions', '4', 'Add-on (extra charge)', 'Add-on (extra charge)', 'Yes', 'Provides individual problem solving, in-depth clarification of complex subjects, analysis of personal error patterns, preparation for assessments, identification of specific competence gaps, optimization of time management and learning structure, or enhancement of individual performance in selected subjects (available as an optional add-on for an additional fee).', 'Provides individual problem solving, in-depth clarification of complex subjects, analysis of personal error patterns, preparation for assessments, identification of specific competence gaps, optimization of time management and learning structure, or enhancement of individual performance in selected subjects (available as an optional add-on for an additional fee).', 'Provides individual problem solving, in-depth clarification of complex subjects, analysis of personal error patterns, preparation for assessments, identification of specific competence gaps, optimization of time management and learning structure, or enhancement of individual performance in selected subjects (every two weeks, 45 minutes).', 1, ''),
(33, 'College & Career Coaching', '4', 'Add-on (extra charge)', 'Add-on (extra charge)', 'Yes', 'Provides structured college and career coaching covering college selection, application timeline planning, guidance on standardized test strategy such as PSAT/SAT/ACT/AP, essay and document review, scholarship and financial-aid guidance, interview training, course alignment with college requirements, and progress monitoring (available as an optional add-on for an additional fee).', 'Provides structured college and career coaching covering college selection, application timeline planning, guidance on standardized test strategy such as PSAT/SAT/ACT/AP, essay and document review, scholarship and financial-aid guidance, interview training, course alignment with college requirements, and progress monitoring (available as an optional add-on for an additional fee).', 'Provides structured college and career coaching covering college selection, application timeline planning, guidance on standardized test strategy such as PSAT/SAT/ACT/AP, essay and document review, scholarship and financial-aid guidance, interview training, course alignment with college requirements, and progress monitoring (3 sessions in Grade 11 and 3 sessions in Grade 12; 45 minutes each).', 1, ''),
(34, 'Digital Transcript', '5', 'Yes', 'Yes', 'Yes', 'Provides an automatically updated digital transcript accessible in both student and parent dashboards, displaying completed subjects and corresponding grades immediately after each exam, ensuring continuous and transparent performance tracking throughout the entire study period.', 'Provides an automatically updated digital transcript accessible in both student and parent dashboards, displaying completed subjects and corresponding grades immediately after each exam, ensuring continuous and transparent performance tracking throughout the entire study period.', 'Provides an automatically updated digital transcript accessible in both student and parent dashboards, displaying completed subjects and corresponding grades immediately after each exam, ensuring continuous and transparent performance tracking throughout the entire study period.', 1, ''),
(35, 'High School President’s Reference Letter', '5', 'Yes', 'Add-on (extra charge)', 'Yes', 'Provides a personalized reference letter from the High School President, issued upon request to support college applications, scholarship considerations, or professional career opportunities (subject to a handling and shipping fee for preparation and processing).', 'Provides a personalized reference letter from the High School President, issued upon request to support college applications, scholarship considerations, or professional career opportunities.', 'Provides a personalized reference letter from the High School President, issued upon request to support college applications, scholarship considerations, or professional career opportunities.', 1, ''),
(36, 'Diploma Package', '5', 'Add-on (extra charge)', 'Add-on (extra charge)', 'Yes', 'Provides a physical High School Diploma together with the official transcript, presented in a premium leather folder and delivered securely to the student or parents by courier service after graduation (subject to a handling and shipping fee).', 'Provides a physical High School Diploma together with the official transcript, presented in a premium leather folder and delivered securely to the student or parents by courier service after graduation (subject to a handling and shipping fee).', 'Provides a physical High School Diploma together with the official transcript, presented in a premium leather folder and delivered securely to the student or parents by courier service after graduation.', 1, ''),
(37, 'Student Educational Help Desk', '5', 'Priority', 'Standard', 'High Priority', 'Provides a dedicated parent Help Desk for inquiries related to student progress, exam schedules, access issues, or administrative questions, handled through a ticket system and answered by the responsible mentor or staff member. Standard processing time applies.Provides a structured educational Help Desk for subject-related questions and exam preparation support, where students can submit inquiries through a ticket system and receive responses from the responsible mentor. Standard processing time applies.Provides a structured educational Help Desk for subject-related questions and exam preparation support, where students can submit inquiries through a ticket system and receive responses from the responsible mentor. Standard processing time applies.', 'Provides a structured educational Help Desk for subject-related questions and exam preparation support, where students can submit inquiries through a ticket system and receive responses from the responsible mentor. Priority processing time applies.', 'Provides a structured educational Help Desk for subject-related questions and exam preparation support, where students can submit inquiries through a ticket system and receive responses from the responsible mentor. High-priority processing time applies.', 1, ''),
(38, 'Parent Help Desk', '5', 'Priority', 'Standard', 'High Priority', 'Provides a dedicated parent Help Desk for inquiries related to student progress, exam schedules, access issues, or administrative questions, handled through a ticket system and answered by the responsible mentor or staff member. Standard processing time applies.', 'Provides a dedicated parent Help Desk for inquiries related to student progress, exam schedules, access issues, or administrative questions, handled through a ticket system and answered by the responsible mentor or staff member. Priority processing time applies.', 'Provides a dedicated parent Help Desk for inquiries related to student progress, exam schedules, access issues, or administrative questions, handled through a ticket system and answered by the responsible mentor or staff member. High-priority processing time applies.', 1, ''),
(39, 'Family Consultation', '5', '1 per year', 'Parent Help Desk', '2 per year', 'Family consultation is provided through the Parent Help Desk, allowing parents to address all concerns and receive guidance via the ticket system.', 'Includes one annual face-to-face family consultation with the assigned mentor to discuss student progress, learning goals, and individual development.', 'Includes two annual face-to-face family consultations with the assigned mentor to discuss student progress, learning goals, and individual development.', 1, ''),
(40, 'College-Level Examination Program (CLEP) Prep-Courses with Pre-Exams', '3', '1 per year', 'Add-on (extra charge)', '2 per year', 'College-Level Examination Program (CLEP) preparation courses with a simulated exam available as an optional add-on for an additional fee.', 'College-Level Examination Program (CLEP) preparation courses with a simulated exam included in the plan (1 course of choice within 12 months).', 'College-Level Examination Program (CLEP) preparation courses with a simulated exam included in the plan (2 courses of choice within 12 months).', 4, 'college-level-examination'),
(41, 'English Courses for Speakers of other Languages (ESOL) with Exam', '3', 'Add-on (extra charge)', 'Add-on (extra charge)', '1 per year', 'U.S. state-approved English language development courses with a final exam available as an optional add-on for an additional fee.', 'U.S. state-approved English language development courses with a final exam available as an optional add-on for an additional fee.', 'U.S. state-approved English language development courses with a final exam included in the plan (1 course per year).', 6, 'english-courses-for-speakers');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `features`
--
ALTER TABLE `features`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `features`
--
ALTER TABLE `features`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
